stages:
  - build

image: ghcr.io/cross-rs/aarch64-unknown-linux-gnu

Build-RPi3:
  stage: build
  script:
    - "make armstub -B"
    - "cp ci/adesto-512 include/memory_defines.h"
    - "make RPI_VERSION=3 RPI_BPLUS=0 -j4 -B"
    - "mv kernel8.img kernel8-adesto-512-rpi3.img"
    - "cp ci/adesto-cal include/memory_defines.h"
    - "make RPI_VERSION=3 RPI_BPLUS=0 -j4 -B"
    - "mv kernel8.img kernel8-adesto-cal-rpi3.img"
    - "cp ci/fujitsu-512 include/memory_defines.h"
    - "make RPI_VERSION=3 RPI_BPLUS=0 -j4 -B"
    - "mv kernel8.img kernel8-fujitsu-512-rpi3.img"
    - "cp ci/fujitsu-cal include/memory_defines.h"
    - "make RPI_VERSION=3 RPI_BPLUS=0 -j4 -B"
    - "mv kernel8.img kernel8-fujitsu-cal-rpi3.img"
  artifacts:
    expire_in: never
    name: "RPi3 Files"
    paths:
      - "armstub-new.bin"
      - "config.txt"
      - "kernel8-*.img"

Build-RPi3B+:
  stage: build
  script:
    - "make armstub -B"
    - "cp ci/adesto-512 include/memory_defines.h"
    - "make RPI_VERSION=3 RPI_BPLUS=1 -j4 -B"
    - "mv kernel8.img kernel8-adesto-512-rpi3b+.img"
    - "cp ci/adesto-cal include/memory_defines.h"
    - "make RPI_VERSION=3 RPI_BPLUS=1 -j4 -B"
    - "mv kernel8.img kernel8-adesto-cal-rpi3b+.img"
    - "cp ci/fujitsu-512 include/memory_defines.h"
    - "make RPI_VERSION=3 RPI_BPLUS=1 -j4 -B"
    - "mv kernel8.img kernel8-fujitsu-512-rpi3b+.img"
    - "cp ci/fujitsu-cal include/memory_defines.h"
    - "make RPI_VERSION=3 RPI_BPLUS=1 -j4 -B"
    - "mv kernel8.img kernel8-fujitsu-cal-rpi3b+.img"
  artifacts:
    expire_in: never
    name: "RPi3B+ Files"
    paths:
      - "armstub-new.bin"
      - "config.txt"
      - "kernel8-*.img"

Build-RPi4:
  stage: build
  script:
    - "make armstub -B"
    - "cp ci/adesto-512 include/memory_defines.h"
    - "make RPI_VERSION=4 RPI_BPLUS=0 -j4 -B"
    - "mv kernel8.img kernel8-adesto-512-rpi4.img"
    - "cp ci/adesto-cal include/memory_defines.h"
    - "make RPI_VERSION=4 RPI_BPLUS=0 -j4 -B"
    - "mv kernel8.img kernel8-adesto-cal-rpi4.img"
    - "cp ci/fujitsu-512 include/memory_defines.h"
    - "make RPI_VERSION=4 RPI_BPLUS=0 -j4 -B"
    - "mv kernel8.img kernel8-fujitsu-512-rpi4.img"
    - "cp ci/fujitsu-cal include/memory_defines.h"
    - "make RPI_VERSION=4 RPI_BPLUS=0 -j4 -B"
    - "mv kernel8.img kernel8-fujitsu-cal-rpi4.img"
  artifacts:
    expire_in: never
    name: "RPi4 Files"
    paths:
      - "armstub-new.bin"
      - "config.txt"
      - "kernel8-*.img"
