stages:
  - build

image: ghcr.io/cross-rs/aarch64-unknown-linux-gnu

Build-RPi3:
  stage: build
  script:
    - "make armstub -B"
    - "./compile.sh 3 0 1 256"
    - "mv kernel8.img kernel8-adesto-512-rpi3.img"
    - "./compile.sh 3 0 1 256"
    - "mv kernel8.img kernel8-adesto-256-rpi3.img"
    - "./compile.sh 3 0 1 128"
    - "mv kernel8.img kernel8-adesto-128-rpi3.img"
    - "./compile.sh 3 0 1 64"
    - "mv kernel8.img kernel8-adesto-64-rpi3.img"
    - "./compile.sh 3 0 2 512"
    - "mv kernel8.img kernel8-fujitsu-512-rpi3.img"
    - "./compile.sh 3 0 2 256"
    - "mv kernel8.img kernel8-fujitsu-256-rpi3.img"
    - "./compile.sh 3 0 2 128"
    - "mv kernel8.img kernel8-fujitsu-128-rpi3.img"
    - "./compile.sh 3 0 2 64"
    - "mv kernel8.img kernel8-fujitsu-64-rpi3.img"
    - "./compile.sh 3 0 2 32"
    - "mv kernel8.img kernel8-fujitsu-32-rpi3.img"
  artifacts:
    expire_in: never
    name: "RPi3 Files"
    paths:
      - "armstub-new.bin"
      - "config.txt"
      - "kernel8-*.img"

Build-RPi3B+:
  stage: build
  script:
    - "make armstub -B"
    - "./compile.sh 3 1 1 512"
    - "mv kernel8.img kernel8-adesto-512-rpi3b+.img"
    - "./compile.sh 3 1 1 256"
    - "mv kernel8.img kernel8-adesto-256-rpi3b+.img"
    - "./compile.sh 3 1 1 128"
    - "mv kernel8.img kernel8-adesto-128-rpi3b+.img"
    - "./compile.sh 3 1 1 64"
    - "mv kernel8.img kernel8-adesto-64-rpi3b+.img"
    - "./compile.sh 3 1 2 512"
    - "mv kernel8.img kernel8-fujitsu-512-rpi3b+.img"
    - "./compile.sh 3 1 2 256"
    - "mv kernel8.img kernel8-fujitsu-256-rpi3b+.img"
    - "./compile.sh 3 1 2 128"
    - "mv kernel8.img kernel8-fujitsu-128-rpi3b+.img"
    - "./compile.sh 3 1 2 64"
    - "mv kernel8.img kernel8-fujitsu-64-rpi3b+.img"
    - "./compile.sh 3 1 2 32"
    - "mv kernel8.img kernel8-fujitsu-32-rpi3b+.img"
  artifacts:
    expire_in: never
    name: "RPi3B+ Files"
    paths:
      - "armstub-new.bin"
      - "config.txt"
      - "kernel8-*.img"

Build-RPi4:
  stage: build
  script:
    - "make armstub -B"
    - "./compile.sh 4 0 1 512"
    - "mv kernel8.img kernel8-adesto-512-rpi4.img"
    - "./compile.sh 4 0 1 256"
    - "mv kernel8.img kernel8-adesto-256-rpi4.img"
    - "./compile.sh 4 0 1 128"
    - "mv kernel8.img kernel8-adesto-128-rpi4.img"
    - "./compile.sh 4 0 1 64"
    - "mv kernel8.img kernel8-adesto-64-rpi4.img"
    - "./compile.sh 4 0 2 512"
    - "mv kernel8.img kernel8-fujitsu-512-rpi4.img"
    - "./compile.sh 4 0 2 256"
    - "mv kernel8.img kernel8-fujitsu-256-rpi4.img"
    - "./compile.sh 4 0 2 128"
    - "mv kernel8.img kernel8-fujitsu-128-rpi4.img"
    - "./compile.sh 4 0 2 64"
    - "mv kernel8.img kernel8-fujitsu-64-rpi4.img"
    - "./compile.sh 4 0 2 32"
    - "mv kernel8.img kernel8-fujitsu-32-rpi4.img"
  artifacts:
    expire_in: never
    name: "RPi4 Files"
    paths:
      - "armstub-new.bin"
      - "config.txt"
      - "kernel8-*.img"
