stages:
  - build

image: ghcr.io/cross-rs/aarch64-unknown-linux-gnu

Build:
  stage: build
  before_script:
    - "apt install -y wget"
  script:
    - "git submodule init"
    - "git submodule update"
    - "./init.sh"
    - "make -j6 boot"
  artifacts:
    expire_in: never
    name: "Boot Files"
    paths:
      - "boot/*"
