stages:
  - build

image: ghcr.io/cross-rs/aarch64-unknown-linux-gnu

Build:
  stage: build
  script:
    - "rm -rf circle/*"
    - "git submodule init"
    - "git submodule update"
    - "./init.sh"
    - "make -j6"
    - "cp -R circle/boot/* boot/*"
    - "cp kernel*.img boot/*"
    - "cp boot/config64.txt boot/config.txt"
  artifacts:
    expire_in: never
    name: "Boot Files"
    paths:
      - "boot/*"
