stages:
  - build

image: ghcr.io/cross-rs/aarch64-unknown-linux-gnu

Build:
  stage: build
  before_script:
    - "apt install -y wget"
    - "git submodule init"
    - "git submodule update"
    - "./init.sh"
  script:
    - "./compile.sh 1 780000 kernel8-adesto-512"
    - "./compile.sh 1 1560000 kernel8-adesto-256"
    - "./compile.sh 1 3120000 kernel8-adesto-128"
    - "./compile.sh 1 6240000 kernel8-adesto-64"
    - "./compile.sh 2 780000 kernel8-fujitsu-512"
    - "./compile.sh 2 1560000 kernel8-fujitsu-256"
    - "./compile.sh 2 3120000 kernel8-fujitsu-128"
    - "./compile.sh 2 6240000 kernel8-fujitsu-64"
    - "./compile.sh 2 12480000 kernel8-fujitsu-32"
  artifacts:
    expire_in: never
    name: "Boot Files"
    paths:
      - "boot/*"
